default: &default
  adapter: postgresql
  encoding: unicode
  # comment out next line for Docker
  host: localhost

  # Uncomment next 3 lines for Docker
  # host: db
  # username: postgres
  # password:
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
